server:
  port: ${SERVER_PORT:8002}

spring:
  application:
    name: scan_runner
  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}
      group-id: group_id
    producer:
      bootstrap-servers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}
  datasource:
    url: jdbc:postgresql://${POSTGRESQL_HOST:localhost}:${POSTGRESQL_PORT:5432}/mend
    username: postgres
    password: #
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: info
    org.springframework.web: debug
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

topic:
  name:
    consumer: scan.runner
    producer: scan.runner


auto:
  create:
    topics:
      enable: true


# Actuator property - performance impact
management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: always

